#define MONITOR_COUNT 1
#define DESKTOP_COUNT 6

#define WINDOW_LAYOUT_DEFAULT WINDOW_LAYOUT_TILED_MASTER
#define WINDOW_INITIAL_GAP 10

#define SHOW_DECORATION false;
#define BAR_START_MONITOR 0

#define WM_TERMINATE_KEY XK_C
#define MASTER_KEY Mod4Mask
